import Head from "next/head";
import { Future, HowWork, Browser } from "components";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <div className="bg-app h-fit">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box className="p-0 m-0 flex justify-center items-center flex-col select-none">
        <Browser />
        <Future />
        <HowWork />
      </Box>
    </div>
  );
}
